<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpsDesk.Application\OpsDesk.Application.csproj" />
    <ProjectReference Include="..\OpsDesk.Domain\OpsDesk.Domain.csproj" />
    <ProjectReference Include="..\OpsDesk.Shared\OpsDesk.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
